-- creation database
CREATE DATABASE IF NOT EXISTS `mybooksdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
-- creation table books in database
CREATE TABLE IF NOT EXISTS `mybooksdb`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `pages` INT NULL,
  `chapterTitle` VARCHAR(45) NULL,
  `chapterContent` LONGTEXT NULL,
    `resume` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));

-- ajouter livres dans table books
INSERT INTO `mybooksdb`.`books` (`id`, `title`, `author`, `pages`, `chapterTitle`, `chapterContent`, `resume`) VALUES (1, 'Le Petit Prince', 'Antoine de Saint-Exupéry', 96, 'Le Petit Prince', 'Le Petit Prince est un conte philosophique écrit par Antoine de Saint-Exupéry et publié en 1943. Il est dédié à « un ami », le pilote de ligne Robert de La Rochefoucauld, qui s''est écrasé en 1942 en Afrique du Nord. Le Petit Prince est un conte philosophique écrit par Antoine de Saint-Exupéry et publié en 1943. Il est dédié à « un ami », le pilote de ligne Robert de La Rochefoucauld, qui s''est écrasé en 1942 en Afrique du Nord.', 'Le Petit Prince est un conte philosophique écrit par Antoine de Saint-Exupéry et publié en 1943. Il est dédié à « un ami », le pilote de ligne Robert de La Rochefoucauld, qui s''est écrasé en 1942 en Afrique du Nord.');
INSERT INTO `mybooksdb`.`books` (`id`, `title`, `author`, `pages`, `chapterTitle`, `chapterContent`, `resume`) VALUES (2, 'Le Seigneur des Anneaux', 'J. R. R. Tolkien', 1216, 'La Communauté de l''anneau', 'La Communauté de l''anneau est le premier tome de la trilogie Le Seigneur des anneaux, écrite par J. R. R. Tolkien. Il est publié en 1954. La Communauté de l''anneau est le premier tome de la trilogie Le Seigneur des anneaux, écrite par J. R. R. Tolkien. Il est publié en 1954.', 'La Communauté de l''anneau est le premier tome de la trilogie Le Seigneur des anneaux, écrite par J. R. R. Tolkien. Il est publié en 1954.');
INSERT INTO `mybooksdb`.`books` (`id`, `title`, `author`, `pages`, `chapterTitle`, `chapterContent`, `resume`) VALUES (3, 'Harry Potter', 'J. K. Rowling', 309, 'Harry Potter à l''école des sorciers', 'Harry Potter à l''école des sorciers est le premier tome de la série littéraire Harry Potter, écrite par J. K. Rowling. Il est publié en 1997. Harry Potter à l''école des sorciers est le premier tome de la série littéraire Harry Potter, écrite par J. K. Rowling. Il est publié en 1997.', 'Harry Potter à l''école des sorciers est le premier tome de la série littéraire Harry Potter, écrite par J. K. Rowling. Il est publié en 1997.');
INSERT INTO `mybooksdb`.`books` (`id`, `title`, `author`, `pages`, `chapterTitle`, `chapterContent`, `resume`) VALUES (4, 'Le Hobbit', 'J. R. R. Tolkien', 310, 'La Communauté de l''anneau', 'La Communauté de l''anneau est le premier tome de la trilogie Le Seigneur des anneaux, écrite par J. R. R. Tolkien. Il est publié en 1954. La Communauté de l''anneau est le premier tome de la trilogie Le Seigneur des anneaux, écrite par J. R. R. Tolkien. Il est publié en 1954.', 'La Communauté de l''anneau est le premier tome de la trilogie Le Seigneur des anneaux, écrite par J. R. R. Tolkien. Il est publié en 1954.');
INSERT INTO `mybooksdb`.`books` (`id`, `title`, `author`, `pages`, `chapterTitle`, `chapterContent`, `resume`) VALUES (5, 'Le Monde de Narnia', 'C. S. Lewis', 778, 'Le Lion, la Sorcière Blanche et l''Armoire Magique', 'Le Lion, la Sorcière Blanche et l''Armoire Magique est le premier tome de la série littéraire Le Monde de Narnia, écrite par C. S. Lewis. Il est publié en 1950. Le Lion, la Sorcière Blanche et l''Armoire Magique est le premier tome de la série littéraire Le Monde de Narnia, écrite par C. S. Lewis. Il est publié en 1950.', 'Le Lion, la Sorcière Blanche et l''Armoire Magique est le premier tome de la série littéraire Le Monde de Narnia, écrite par C. S. Lewis. Il est publié en 1950.');
INSERT INTO `mybooksdb`.`books` (`id`, `title`, `author`, `pages`, `chapterTitle`, `chapterContent`, `resume`) VALUES (6, 'Le Journal d''Anne Frank', 'Anne Frank', 296, 'Le Journal d''Anne Frank', 'Le Journal d''Anne Frank est un livre écrit par Anne Frank, une jeune fille juive de 13 ans, entre le 12 juin 1942 et le 1er août 1944. Le Journal d''Anne Frank est un livre écrit par Anne Frank, une jeune fille juive de 13 ans, entre le 12 juin 1942 et le 1er août 1944.', 'Le Journal d''Anne Frank est un livre écrit par Anne Frank, une jeune fille juive de 13 ans, entre le 12 juin 1942 et le 1er août 1944.');
INSERT INTO `mybooksdb`.`books` (`id`, `title`, `author`, `pages`, `chapterTitle`, `chapterContent`, `resume`) VALUES (8, 'Le Trône de fer', 'George R. R. Martin', 835, 'Le Trône de fer', 'Le Trône de fer est le premier tome de la série littéraire Le Trône de fer, écrite par George R. R. Martin. Il est publié en 1996. Le Trône de fer est le premier tome de la série littéraire Le Trône de fer, écrite par George R. R. Martin. Il est publié en 1996.', 'Le Trône de fer est le premier tome de la série littéraire Le Trône de fer, écrite par George R. R. Martin. Il est publié en 1996.');

--replace books number of pages of the book with id 1
UPDATE `mybooksdb`.`books` SET `pages` = '1000' WHERE (`id` = '1');